## we can create array using numpy array

In [1]:
import numpy as np

a = np.array([1,2,3])
print()

[1 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [13]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
# np.arange 
np.arange(1,11,2) # as like python range function

array([1, 3, 5, 7, 9])

In [20]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.random.random((3,4))

array([[0.32480886, 0.97487739, 0.46505121, 0.95378852],
       [0.18172135, 0.62071008, 0.42319478, 0.8325279 ],
       [0.84586291, 0.96569658, 0.47299344, 0.82723084]])

In [34]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [36]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [63]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=int).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [43]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
#ndim
a3.ndim

3

In [53]:
a3.shape

(2, 2, 2)

In [55]:
a3.size

8

In [59]:
# itemsize
a3.itemsize

8

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a2[1, ::3]

array([4, 7])

In [107]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [111]:
a3 = np.arange(27).reshape(3,3,3)

In [113]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
a3[1,:,1]

array([10, 13, 16])

In [163]:
a3[2,:2, 1:]

array([[19, 20],
       [22, 23]])

# Reshaping

In [167]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [169]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [171]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [173]:
#ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])